### ISSUE TITLE
measure the distance between two moving platforms(moving base and moving rover)? 

### ISSUE THREAD

**Issue by won13y** [PaulBouchier/swiftnav_piksi#5]
I tried to use the following ROS pacakage

http://wiki.ros.org/swiftnav_piksi

in your wiki

"Other configurations of two modules are possible, such as placing both on moving platforms"

Likewise, I would like to measure the distance between two moving platforms(Not the stationary base station)

That is, both base and rover station are moving, and the distance between base and rover station is the thing that I would like to measure.

Would you please let me know how to set the parameter for me to  measure the distance between two moving platforms?

**Comment by PaulBouchier** [comment]
There are no parameters to set. Piksi measures the distance north & east (lattitude & longitude) between the two receivers. If you set both on moving platforms, it should in theory report the distance between them. I have not tried this, to verify it works, but it is a function of the basic operation of Piksi RTK GPS. (Read about RTK GPS on Wikipedia). Swiftnav's documentation seems to indicate it is possible, but I don't know if there are any limitations.
