### ISSUE TITLE
Does it support for ROS Kinetic ?

### ISSUE THREAD

**Issue by lastflowers** [PaulBouchier/swiftnav_piksi#9]
I'v read that this package supports indigo and jade.
I am wondering I can run the package under kinetic.

Thank you in advance.

**Comment by PaulBouchier** [comment]
It should support kinetic - there is nothing in it that's release-specific. I haven't tested it though.

Swiftnav has taken over maintenance of the driver and you should now use their version, which is in this repo: https://github.com/swift-nav/swiftnav_ros
I have marked the swiftnav_piksi driver as obsolete

@jkretzmer I think you need to add content to README.md and clarify whether your driver supports the original pikis as well as piksi multi.
